# Lo que importa para el evento (lo demas, como venga). El resto del archivo lo crea el servidor.
level-type=backrooms_evento\:nivel_0
online-mode=false
enforce-secure-profile=false
difficulty=normal
gamemode=adventure
force-gamemode=false
max-players=250
spawn-protection=0
allow-flight=false
view-distance=6
simulation-distance=4
motd=BACKROOMS - Nivel 0
sync-chunk-writes=false
